# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "aarch64-qemu-virt"
# Platform family.
family = "aarch64-qemu-virt"

# Base address of the whole physical memory.
phys-memory-base = "0x4000_0000"
# Size of the whole physical memory.
# phys-memory-size = "0x800_0000"     # 128M
# phys-memory-size = "0x4000_0000"     # 1G
phys-memory-size = "0x3000_0000" # 768M
# phys-memory-size = "0xc000_0000"     # 3G
# phys-memory-size = "0x1_0000_0000"     # 4G
# phys-memory-size = "0x1_8000_0000"     # 6G
# phys-memory-size = "0x2_0000_0000"     # 8G
# Base physical address of the kernel image.
kernel-base-paddr = "0x4008_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_4008_0000"
# virtual start address of the mapping memory.
mmap-start-vaddr = "0xffff_8000_0000_0000"
# virtual end address of the mapping memory.
mmap-end-vaddr = "0xffff_f000_0000_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    [
        "0x3000_0000",
        "0x40_0000",
    ], # bus@30000000
    [
        "0x3080_0000",
        "0x40_0000",
    ], # bus@30800000
    [
        "0x3880_0000",
        "0x14_0000",
    ], # GICv3
    [
        "0x0a00_0000",
        "0x4000",
    ], # VirtIO
]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = [
    # ["0x0a00_0000", "0x200"],
    # ["0x0a00_0200", "0x200"],
    # ["0x0a00_0400", "0x200"],
    # ["0x0a00_0600", "0x200"],
    # ["0x0a00_0800", "0x200"],
    # ["0x0a00_0a00", "0x200"],
    # ["0x0a00_0c00", "0x200"],
    # ["0x0a00_0e00", "0x200"],
    # ["0x0a00_1000", "0x200"],
    # ["0x0a00_1200", "0x200"],
    # ["0x0a00_1400", "0x200"],
    # ["0x0a00_1600", "0x200"],
    # ["0x0a00_1800", "0x200"],
    # ["0x0a00_1a00", "0x200"],
    # ["0x0a00_1c00", "0x200"],
    # ["0x0a00_1e00", "0x200"],
    # ["0x0a00_3000", "0x200"],
    # ["0x0a00_2200", "0x200"],
    # ["0x0a00_2400", "0x200"],
    # ["0x0a00_2600", "0x200"],
    # ["0x0a00_2800", "0x200"],
    # ["0x0a00_2a00", "0x200"],
    # ["0x0a00_2c00", "0x200"],
    # ["0x0a00_2e00", "0x200"],
    # ["0x0a00_3000", "0x200"],
    # ["0x0a00_3200", "0x200"],
    ["0x0a00_3400", "0x200"],
    # ["0x0a00_3600", "0x200"],
    ["0x0a00_3800", "0x200"],
    # ["0x0a00_3a00", "0x200"],
    # ["0x0a00_3c00", "0x200"],
    # ["0x0a00_3e00", "0x200"],
]

# Base physical address of the PCIe ECAM space.
pci-ecam-base = "0x0"
# End PCI bus number (`bus-range` property in device tree).
pci-bus-end = "0x0"
# PCI device memory ranges (`ranges` property in device tree).
pci-ranges = [
    ["0x0", "0x0"],          # PIO space
    ["0x0", "0x0"],       # 32-bit MMIO space
    ["0x0", "0x0"], # 64-but MMIO space
]

# UART Address
# uart-paddr = "0x0900_0000"
# uart-paddr = "0x3089_0000"
uart-paddr = "0x30a6_0000"
uart-irq = "61"

# # Virtio console
virtio-console-paddr = "0xa003800"
# # Virtio console IRQ
virtio-console-irq = "44"

# GICC Address
gicc-paddr = "0x0"
gicd-paddr = "0x3880_0000"
gicr-paddr = "0x3888_0000"

# PSCI
psci-method = "smc"

# Device tree blob address
DTB_ADDR = "0x40000000"