name: Test CI

on: [push, pull_request]

env:
  qemu-version: 7.1.0
  rust-toolchain: nightly-2023-09-01

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.rust-toolchain }}
        components: rust-src, llvm-tools-preview
    - name: Run unit tests
      run: make unittest_no_fail_fast

  app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        arch: [x86_64, riscv64, aarch64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ env.rust-toolchain }}
        components: rust-src, llvm-tools-preview
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-binutils
        version: 0.3.5
        use-tool-cache: true
    - name: Install gcc multilib
      run: sudo apt update && sudo apt install -y gcc-multilib
    - uses: ./.github/workflows/actions/setup-qemu
      with:
        qemu-version: ${{ env.qemu-version }}
    - uses: ./.github/workflows/actions/setup-musl
      with:
        arch: ${{ matrix.arch }}
    - name: Run app tests
      run: |
        make disk_img
        make test ARCH=${{ matrix.arch }}
